{{- $fullName := include "app-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: otus.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80

    - host: grafana.otus.homework
      http:
        paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: {{ .Values.grafana.name }}
                  port:
                    number: 80
    - host: prometheus.otus.homework
      http:
        paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: {{ .Values.prometheus.name }}
                  port:
                    number: 9090

