apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-chart.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    any: true
  endpoints:
  - interval: 10s
    path: /metrics