apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "app-chart.fullname" . }}
  namespaceSelector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
  selector:
    matchLabels:
      {{- include "app-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    targetPort: 8000
    path: /metrics