replicaCount: 1

fullnameOverride: "app"

image:
  repository: legioner4/otis-work-app:5.2


service:
  type: NodePort
  port: 80
  targetPort: 8000


postgresql:
  enabled: true
  postgresqlUsername: appuser
  postgresqlPassword: apppasswd
  postgresqlDatabase: appdb
  persistence:
    size: 0.1Gi
  service:
    port: "5432"